### ISSUE TITLE
API not working issue with selenium using to much RAM on the server.

### ISSUE THREAD

**Issue by mayanktolani19** [Codebotics/VITask#11]

**Comment by apratimshukla6** [comment]
How many requests before the server restarts?

**Comment by uragirii** [comment]
How about we shift to a NodeJS server? We can use `pupeeter` . Imo nodejs should use less RAM

Also are we closing driver after use? It will save memory

**Comment by apratimshukla6** [comment]
Yeah currently I fixed the issue by closing the driver and fetching everything at once.Let's see,there is scope of moving to nodejs in future...
