### ISSUE TITLE
TimeTable API is not sorted and Labs are different

### ISSUE THREAD

**Issue by uragirii** [Codebotics/VITask#18]
The classes in TimeTable are not sorted according to the time but first sorted classes and then sorted Labs are there.

Also, combine lab slots together, this can be easily done in Python and difficult in JS

**Comment by apratimshukla6** [comment]
The TimeTable is now sorted, I'll see if we can combine lab slots together for our local system instead of the public API.

**Comment by uragirii** [comment]
Fixed issue on client side (App)
