### ISSUE TITLE
Non Uniform API Structure

### ISSUE THREAD

**Issue by apratimshukla6** [Codebotics/VITask#34]
Different APIs have different structures to store the same data. For example `api/vtop/sync` stores attendance in a slightly different structure as compared to `api/vtop/attendance`
_This matter is currently under investigation_

**Comment by uragirii** [comment]
`/api/vtop/sync` returns both attendance and marks right? So, it returns attendance object and marks object?

**Comment by apratimshukla6** [comment]
Yeah but there were slight changes in the object structure (mainly slots), I have fixed it for attendance (not deployed yet). I will keep on investigating for other APIs.

**Comment by apratimshukla6** [comment]
This issue has been fixed. Reopen if anyone finds more non-uniformity.
